github.com:
    users:
        DARFT-software:
            oauth_token: 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
    git_protocol: https
    user: DARFT-software
    oauth_token: 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
