github.com:
    users:
        DARFT-software:
            oauth_token: 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
    git_protocol: https
    user: DARFT-software
    oauth_token: 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
